# Generated by Django 4.0.3 on 2022-03-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'deadline']},
        ),
    ]
