# Generated by Django 4.0.3 on 2022-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_task_options_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
