# Generated by Django 4.0.3 on 2022-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(verbose_name='I am currently doing this'),
        ),
    ]
